### ISSUE TITLE
Add file based configuration

### ISSUE THREAD

**Issue by KevinGimbel** [kevingimbel/vhost#1]
Beside the `template.conf` file there should be a generic configuration file to define where to put the files, e.g. 

``` yaml
document_root: /var/www
create_index_html: true
use_symlinks: false
```

Need to check if "yaml"-like or JSON or another format is better to parse from a bash script. Otherwise may use environment variables.
